# Generated by Django 4.0.6 on 2022-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_open',
            field=models.BooleanField(default=False),
        ),
    ]
