# Generated by Django 4.0.6 on 2022-07-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_gamesession_game_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=1, unique=True)),
                ('player_name', models.CharField(max_length=200)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesessionhistory',
            name='turn_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='GameSessionPlayers',
        ),
        migrations.AddField(
            model_name='gamesessionhistory',
            name='player_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='game_manager.gamesessionplayer'),
        ),
    ]
