# Generated by Django 4.0.6 on 2022-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_gamesessionplayer_gamesessionhistory_turn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
