# Generated by Django 4.0.6 on 2022-07-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_alter_gamesession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesessionhistory',
            name='session_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game_manager.gamesession'),
        ),
        migrations.AlterField(
            model_name='gamesessionplayer',
            name='session_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game_manager.gamesession'),
        ),
    ]
